# Generated by Django 5.1.2 on 2024-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_material_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='qty',
            field=models.FloatField(),
        ),
    ]
