# Generated by Django 5.1.2 on 2024-11-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_material_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
