# Generated by Django 5.1.2 on 2024-11-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_project_area_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='markup_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
