# Generated by Django 5.1.2 on 2024-11-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_material_markup_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='markup_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
